server:
  port: 8768

spring:
  application:
    name: service-hi-mqs

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
feign.hystrix.enabled: true

spring.redis.host: 192.168.223.43
spring.redis.port: 6379
spring.redis.password: guohuaiGUO4056
spring.redis.database: 3

# hazelcast缓存配置
spring.hazelcast.config: file:${user.dir}/config/hazelcast.xml

spring.datasource.name: dataSource
spring.datasource.url: jdbc:h2:mem:gh_mimosa;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;REFERENTIAL_INTEGRITY=FALSE
spring.datasource.username: root
spring.datasource.password: guohuaiGUO4056&

# 参考https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
# 初始化大小，最小，最大连接数
spring.datasource.druid.initial-size: 5
spring.datasource.druid.max-active: 50
spring.datasource.druid.min-idle: 5
# 配置获取连接等待超时的时间
spring.datasource.druid.max-wait: 60000
# 是否缓存preparedStatement，也就是PSCache。
spring.datasource.druid.pool-prepared-statements: false
spring.datasource.druid.max-pool-prepared-statement-per-connection-size: -1
#spring.datasource.druid.max-open-prepared-statements: -1 #和上面的等价
spring.datasource.druid.validation-query: select 1
#spring.datasource.druid.validation-query-timeout:
spring.datasource.druid.test-on-borrow: true
#归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
spring.datasource.druid.test-on-return: false
# 申请连接的时候检测，如果空闲时间大于 timeBetweenEvictionRunsMillis， 执行validationQuery检测连接是否有效。
spring.datasource.druid.test-while-idle: true

#spring.datasource.type: com.alibaba.druid.pool.DruidDataSource
spring.datasource.driver-class-name: org.h2.Driver
#spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.validation-query: select 1
spring.datasource.test-on-borrow: true
spring.data.rest.basePath: /repo

# Hibernate settings are prefixed with spring.jpa.hibernate.*
spring.jpa.database: H2
spring.jpa.open-in-view: true
spring.jpa.hibernate.ddl-auto: create
spring.jpa.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.show-sql: true
spring.jpa.format-sql: true

#logging.config: classpath:logback.xml
logging.config: ${user.dir}/config/logback.xml
logging.path: ${user.dir}/logs

# data
data.debug: true
data.repository.dir: /firconelcm/repo
data.repository.datasourcename: dataSource
data.repository.databasetype: mysql
